name: build-singularity-container
on:
  # Do something on push
  push:
    # Ediot the branches here
    branches:
      - main
      - master
  # Do nothing on pull
  pull_request: []
  
jobs:
  test-build:
    name: "Test build recipe"
    runs-on: ubuntu-latest
    strategy:
      # Keep going on other deployments if anything bloops
      fail-fast: false
      matrix:
        singularity_version:
          - '3.8.4'
    container:
      image: quay.io/singularity/singularity:v${{ matrix.singularity_version }}-slim
      options: --privileged
     
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: build singularity
        run: singularity build ansible-${{ matrix.singularity_version }}.sif Singularity
      - name: Login and Deploy Container 
        run: |         
            echo ${{ secrets.GITHUB_TOKEN }} | singularity remote login -u ${{ secrets.GHCR_USERNAME }} --password-stdin oras://ghcr.io
            singularity push ansible-${{ matrix.singularity_version }}.sif oras://ghcr.io/${GITHUB_REPOSITORY}:${{ matrix.singularity_version }}
      - name: Login and Deploy Container to tag:latest
        if: (matrix.singularity_version == '3.9.4')
        env:
          tag: latest
        run: |         
            echo ${{ secrets.GITHUB_TOKEN }} | singularity remote login -u ${{ secrets.GHCR_USERNAME }} --password-stdin oras://ghcr.io
            singularity push ansible-${{ matrix.singularity_version }}.sif oras://ghcr.io/${GITHUB_REPOSITORY}:${tag}
